config/routes.rb
Rails.application.routes.draw do
  root "welcome#about"
  
  get '/signup', to: "registrations#new"
  post '/signup', to: "registrations#create"

  get 'login', to: "sessions#new"
  post '/login', to: "sessions#create" 
  delete '/logout', to: "sessions#destroy"

  get 'users/:id', to: "users#show", as: "profile"

  resources :chatrooms, param: :slug
  resources :messages
  
  # Serve websocket cable requests in-process
  mount ActionCable.server => '/cable'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/chatroom.rb
class Chatroom < ApplicationRecord
  has_many :messages, dependent: :destroy
  has_many :users, through: :messages

  validates :topic, presence: true, uniqueness: { case_sensitive: false }

  before_validation :sanitize_and_slugify_topic

  def to_param
    slug
  end

  private

  def sanitize_and_slugify_topic
    self.topic = topic.to_s.strip
    self.slug  = topic.downcase.gsub(" ", "-")
  end
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :chatroom
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  has_many :messages
  has_many :chatrooms, through: :messages

  validates :username, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
  helper_method :current_user

  private

  def authenticate_user!
    redirect_to root_path unless current_user
  end

  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end
end

app/controllers/chatrooms_controller.rb
class ChatroomsController < ApplicationController
  before_action :load_chatroom, only: [:edit, :update, :show]

  def index
    @chatroom = Chatroom.new
    @chatrooms = Chatroom.all
  end

  def new
    clear_flash_if_from_chatrooms
    @chatroom = Chatroom.new
  end

  def create
    @chatroom = Chatroom.new(chatroom_params)
    if @chatroom.save
      respond_to do |format|
        format.html { redirect_to @chatroom }
        format.js
      end
    else
      handle_chatroom_creation_error
    end
  end

  def edit
  end

  def update
    if @chatroom.update(chatroom_params)
      redirect_to @chatroom
    else
      handle_chatroom_update_error
    end
  end

  def show
    @message = Message.new
  end

  private

  def load_chatroom
    @chatroom = Chatroom.find_by(slug: params[:slug])
  end

  def chatroom_params
    params.require(:chatroom).permit(:topic)
  end

  def clear_flash_if_from_chatrooms
    flash[:notice] = nil if request.referrer.split("/").last == "chatrooms"
    # request.referrer lấy URL của trang web trước đó mà người dùng đã đến từ.
    # request.referrer.split("/") chia URL thành một mảng các phần, sử dụng dấu gạch chéo (/) làm điểm phân chia.
    # Ví dụ, nếu URL là https://example.com/chatrooms/new, mảng sẽ chứa ["https:", "", "example.com", "chatrooms", "new"].
  end

  def handle_chatroom_creation_error
    flash[:notice] = { error: ["A chatroom with this topic already exists"] }
    respond_to do |format|
      format.html { redirect_to new_chatroom_path }
      format.js { render template: 'chatrooms/chatroom_error.js.erb' }
    end
  end

  def handle_chatroom_update_error
    flash[:notice] = { error: ["Failed to update chatroom"] }
    redirect_to edit_chatroom_path(@chatroom)
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  def create
    message = current_user.messages.new(message_params)
    if message.save
      ActionCable.server.broadcast 'channel_messages', message: message.content, user: message.user.username
      head :ok
      puts "################## produce_message DONE!"
    else
      head :unprocessable_entity
    end
  end

  private

  def message_params
    params.require(:message).permit(:content, :chatroom_id)
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < ApplicationController
  skip_before_action :authenticate_user!

  def new
    @user = User.new
  end

  def create
    user = User.new(user_params)
    if user.save
      sign_in(user)
      redirect_to chatrooms_path
    else
      flash[:error] = user.errors.full_messages.join(", ")
      redirect_to signup_path
    end
  end

  private

  def user_params
    params.require(:user).permit(:username)
  end

  def sign_in(user)
    session[:user_id] = user.id
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :authenticate_user!
  skip_before_action :verify_authenticity_token, only: [:destroy]

  def new
    @user = User.new
  end

  def create
    user = User.find_by(username: user_params[:username])
    if user
      sign_in(user)
      redirect_to chatrooms_path
    else
      flash[:error] = "Username doesn't exist"
      redirect_to login_path
    end
  end

  def destroy
    sign_out
    redirect_to root_path
  end

  private

  def user_params
    params.require(:user).permit(:username)
  end

  def sign_in(user)
    session[:user_id] = user.id
  end

  def sign_out
    reset_session
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  skip_before_action :authenticate_user!

  def about; end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/chatrooms_helper.rb
module ChatroomsHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/chatrooms/_chatroom.html.erb
<ul>
  <li><%= link_to chatroom.topic, chatroom_path(chatroom) %></li>
</ul>

app/views/chatrooms/_chatroom_form.html.erb
<div class="chatroom-form">
  <%= form_for chatroom, remote: true do |f| %>
    <div class="input-group">
      <span class="input-group-addon">Topic:</span>
      <%= f.text_field :topic, class: "form-control" %>
    </div>
    <%= f.submit class: "btn btn-primary", id: "create-chatroom" %>
  <% end %>
</div>

app/views/chatrooms/chatroom_error.js.erb
$("input#chatroom_topic").val(" ");
$("#chatroom-errors").html("<br><%=j render partial: 'layouts/flash_errors', locals: {flash: flash}%>");

app/views/chatrooms/create.js.erb
$("input#chatroom_topic").val(" ")
$("#chatroom-errors").html(" ")
$("#chatroom-index").append('<li><%= link_to @chatroom.topic, chatroom_path(@chatroom) %></li>')

app/views/chatrooms/index.html.erb
<div class="row col-md-8 col-md-offset-2" id="chatroom-title">
  <h1>Chatrooms</h1>
</div>

<div class="row col-md-8 col-md-offset-2" id="chatrooms">
  <%= render partial: 'chatroom_form', locals: { chatroom: @chatroom } %>
  <div id="chatroom-errors">

  </div>
  <ul id="chatroom-index">
    <% if @chatrooms.any? %>
      <%= render @chatrooms %>
    <% else %>
      </ul>
      <p>Be the first one to make a chatroom!</p>
    <% end %>
    </div>

app/views/chatrooms/new.html.erb
<div class="row col-md-8 col-md-offset-2">
  <h1>Create a Chatroom on a programming topic</h1>
  <div class="well">
    <div class="chatroom-form">
      <%= form_for @chatroom do |f| %>
        <div class="input-group">
          <span class="input-group-addon">Topic:</span>
          <%= f.text_field :topic, class: "form-control" %>
        </div>
        <%= f.submit class: "btn btn-primary", id: "create-chatroom" %>
      <% end %>
    </div>
  </div>
  <%= render partial: 'layouts/flash_errors' %>
</div>

app/views/chatrooms/show.html.erb
<div class="row col-md-8 col-md-offset-2">
  <h1><%= @chatroom.topic %></h1>

  <div class="panel panel-default">
    <% if @chatroom.messages.any? %>
      <div class="panel-body" id="messages">
        <%= render partial: 'messages/message', collection: @chatroom.messages %>
      </div>
    <% else %>
      <div class="panel-body hidden" id="messages">
      </div>
    <% end %>
  </div>

  <%= render partial: 'messages/message_form', locals: { message: @message, chatroom: @chatroom } %>
</div>

app/views/layouts/_flash_errors.html.erb
<% if flash.notice %>
  <div class="alert alert-danger">
    <% flash.notice.each do |type, messages| %>
      <span class="glyphicon glyphicon-exclamation-sign" aria-hidden="true"></span>
      <% messages.each do |msg| %>
        <%= type %> <%= msg %>
      <% end %>
    <% end %>
  </div>
<% end %>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Chatting", root_path, class: "navbar-brand" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <%= render partial: 'layouts/navbar_links' %>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/_navbar_links.html.erb
<ul class="nav navbar-nav">
  <% if current_user %>
    <li>
      <%= link_to "New chatroom", new_chatroom_path %>
    </li>
  <% end %>

  <li>
    <%= link_to "Chatrooms", chatrooms_path %>
  </li>
</ul>

<ul class="nav navbar-nav navbar-right">
  <% if current_user %>
    <li>
      <%= link_to "Log Out", logout_path, method: "delete" %>
    </li>
  <% else %>
    <li><%= link_to "Sign Up", signup_path %></li>
    <li><%= link_to "Log In", login_path %></li>
  <% end %>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="vi">
<head>
  <title>Chatting</title>
  <%= csrf_meta_tags %>
  <%= action_cable_meta_tag %>

  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => 'reload' %>
  <%= favicon_link_tag 'favicon.ico' %>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/github-fork-ribbon-css/0.2.0/gh-fork-ribbon.min.css"/>
</head>

<body>
<a class="github-fork-ribbon right-bottom fixed" href="https://github.com/rubyhcm/chat_real_time" title="Fork me on GitHub" target="_blank">
  Fork me on GitHub
</a>

<%= render partial: 'layouts/navbar' %>

<div class="container">
  <%= yield %>
</div>
</body>
</html>

app/views/messages/_message.html.erb
<p><strong><%= message.user.username %>:</strong> <%= message.content %></p>

app/views/messages/_message_form.html.erb
<%= form_for message, remote: true, authenticity_token: true do |f| %>
  <%= f.label :your_message %>:
  <%= f.text_area :content, class: "form-control", data: { textarea: "message" } %>

  <%= f.hidden_field :chatroom_id, value: chatroom.id %>
  <%= f.submit "send", class: "btn btn-primary", style: "display: none", data: { send: "message" } %>
<% end %>

app/views/users/show.html.erb
<h1>Profile</h1>

app/views/welcome/about.html.erb
<div class="jumbotron">
  <h1>Welcome to My Chatting Room!</h1>
  <%if current_user%>
    <p><span class="glyphicon glyphicon-heart"></span> Nice to see you <3 !, <%= current_user.username%> <span class="glyphicon glyphicon-heart"></span></p>
  <%end%>
  <p>Sign up or Log in, then create a chatroom or browse existing rooms to start chatting!!!</p>
</div>